# Generated by Django 5.1.7 on 2025-03-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('id_card', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('number_of_tickets', models.PositiveIntegerField()),
                ('ticket1', models.CharField(blank=True, max_length=50, null=True)),
                ('ticket2', models.CharField(blank=True, max_length=50, null=True)),
                ('ticket3', models.CharField(blank=True, max_length=50, null=True)),
                ('ticket4', models.CharField(blank=True, max_length=50, null=True)),
                ('ticket5', models.CharField(blank=True, max_length=50, null=True)),
                ('ticket6', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
